%% SAVE SIMULATION RESULTS
% Time axis (days)
writematrix(t_instant',[csvdir dirSep 't_instant.csv'])
writematrix(datetime(datevec(t_instant')),[csvdir dirSep 'datetime_sim.csv'])
% Day of year (day number)
writematrix(doy_now',[csvdir dirSep 'doy_now.csv'])
% MATLAB Serial Date Number in Universal Time (UT1)
writematrix(datenum_UT1',[csvdir dirSep 'datenum_UT1.csv'])
% Duration of sunlight (hours)
writematrix(sunh',[csvdir dirSep 'sunh.csv'])
% Air temperature (°C)
writematrix(T_air',[csvdir dirSep 'T_air.csv'])
% Flag: Diapause conditions met (1 = on; 0 = off)
writematrix(diap',[csvdir dirSep 'diap.csv'])
% Accumulated GDDs over the last time step (GDDs)
writematrix(dGDD',[csvdir dirSep 'dGDD.csv'])
% Areal density of chironomid eggs
%writematrix(ad{1,1}',[csvdir dirSep 'ad_chiro_eggs_m.csv'])
%writematrix(ad{1,2}',[csvdir dirSep 'ad_chiro_eggs_f.csv'])
% Areal density of chironomid larvae (1st instar)
%writematrix(ad{2,1}',[csvdir dirSep 'ad_chiro_larvae_1st_m.csv'])
%writematrix(ad{2,2}',[csvdir dirSep 'ad_chiro_larvae_1st_f.csv'])
% Areal density of chironomid larvae (2nd instar)
%writematrix(ad{3,1}',[csvdir dirSep 'ad_chiro_larvae_2nd_m.csv'])
%writematrix(ad{3,2}',[csvdir dirSep 'ad_chiro_larvae_2nd_f.csv'])
% Areal density of chironomid larvae (3rd instar)
%writematrix(ad{4,1}',[csvdir dirSep 'ad_chiro_larvae_3rd_m.csv'])
%writematrix(ad{4,2}',[csvdir dirSep 'ad_chiro_larvae_3rd_f.csv'])
% Areal density of chironomid larvae (4th instar)
%writematrix(ad{5,1}',[csvdir dirSep 'ad_chiro_larvae_4th_m.csv'])
%writematrix(ad{5,2}',[csvdir dirSep 'ad_chiro_larvae_4th_f.csv'])
% Areal density of newly deposed eggs (first age group)
writematrix(ad{1,1}(1,:)',[csvdir dirSep 'ad_chiro_eggs_dep_m.csv'])
writematrix(ad{1,2}(1,:)',[csvdir dirSep 'ad_chiro_eggs_dep_f.csv'])
% Areal density of newly eclosed first-instar larvae (first age group)
writematrix(ad{2,1}(1,:)',[csvdir dirSep 'ad_chiro_larvae_1st_ecl_m.csv'])
writematrix(ad{2,2}(1,:)',[csvdir dirSep 'ad_chiro_larvae_1st_ecl_f.csv'])
% Areal density of newly evolved second-instar larvae (first age group)
writematrix(ad{3,1}(1,:)',[csvdir dirSep 'ad_chiro_larvae_2nd_evo_m.csv'])
writematrix(ad{3,2}(1,:)',[csvdir dirSep 'ad_chiro_larvae_2nd_evo_f.csv'])
% Areal density of newly evolved third-instar larvae (first age group)
writematrix(ad{4,1}(1,:)',[csvdir dirSep 'ad_chiro_larvae_3rd_evo_m.csv'])
writematrix(ad{4,2}(1,:)',[csvdir dirSep 'ad_chiro_larvae_3rd_evo_f.csv'])
% Areal density of newly evolved fourth-instar larvae (first age group)
writematrix(ad{5,1}(1,:)',[csvdir dirSep 'ad_chiro_larvae_4th_evo_m.csv'])
writematrix(ad{5,2}(1,:)',[csvdir dirSep 'ad_chiro_larvae_4th_evo_f.csv'])
% Areal density of emerging chironomid midges (first age group)
writematrix(ad{6,1}(1,:)',[csvdir dirSep 'ad_chiro_mid_eme_m.csv'])
writematrix(ad{6,2}(1,:)',[csvdir dirSep 'ad_chiro_mid_eme_f.csv'])
% Areal density of chironomid midges (all age groups)
%writematrix(ad{6,1}',[csvdir dirSep 'ad_chiro_mid_m.csv'])
%writematrix(ad{6,2}',[csvdir dirSep 'ad_chiro_mid_f.csv'])
% Areal densities: Subtotals
writematrix(ad_subtot{1,1}',[csvdir dirSep 'ad_chiro_eggs_m_subtot.csv'])
writematrix(ad_subtot{1,2}',[csvdir dirSep 'ad_chiro_eggs_f_subtot.csv'])
writematrix(ad_subtot{2,1}',[csvdir dirSep 'ad_chiro_larvae_1st_m_subtot.csv'])
writematrix(ad_subtot{2,2}',[csvdir dirSep 'ad_chiro_larvae_1st_f_subtot.csv'])
writematrix(ad_subtot{3,1}',[csvdir dirSep 'ad_chiro_larvae_2nd_m_subtot.csv'])
writematrix(ad_subtot{3,2}',[csvdir dirSep 'ad_chiro_larvae_2nd_f_subtot.csv'])
writematrix(ad_subtot{4,1}',[csvdir dirSep 'ad_chiro_larvae_3rd_m_subtot.csv'])
writematrix(ad_subtot{4,2}',[csvdir dirSep 'ad_chiro_larvae_3rd_f_subtot.csv'])
writematrix(ad_subtot{5,1}',[csvdir dirSep 'ad_chiro_larvae_4th_m_subtot.csv'])
writematrix(ad_subtot{5,2}',[csvdir dirSep 'ad_chiro_larvae_4th_f_subtot.csv'])
writematrix(ad_subtot{6,1}',[csvdir dirSep 'ad_chiro_mid_m_subtot.csv'])
writematrix(ad_subtot{6,2}',[csvdir dirSep 'ad_chiro_mid_f_subtot.csv'])
% Areal densities: Total Larvae
writematrix(ad_lrv_tot{1,1}',[csvdir dirSep 'ad_chiro_larvae_m_tot.csv'])
writematrix(ad_lrv_tot{1,2}',[csvdir dirSep 'ad_chiro_larvae_f_tot.csv'])
% Ratios: Larvae in each instar to total larvae
writematrix(P_lrv{1,1}',[csvdir dirSep 'P_lrv_1st_m.csv'])
writematrix(P_lrv{1,2}',[csvdir dirSep 'P_lrv_1st_f.csv'])
writematrix(P_lrv{1,3}',[csvdir dirSep 'P_lrv_1st_b.csv'])
writematrix(P_lrv{2,1}',[csvdir dirSep 'P_lrv_2nd_m.csv'])
writematrix(P_lrv{2,2}',[csvdir dirSep 'P_lrv_2nd_f.csv'])
writematrix(P_lrv{2,3}',[csvdir dirSep 'P_lrv_2nd_b.csv'])
writematrix(P_lrv{3,1}',[csvdir dirSep 'P_lrv_3rd_m.csv'])
writematrix(P_lrv{3,2}',[csvdir dirSep 'P_lrv_3rd_f.csv'])
writematrix(P_lrv{3,3}',[csvdir dirSep 'P_lrv_3rd_b.csv'])
writematrix(P_lrv{4,1}',[csvdir dirSep 'P_lrv_4th_m.csv'])
writematrix(P_lrv{4,2}',[csvdir dirSep 'P_lrv_4th_f.csv'])
writematrix(P_lrv{4,3}',[csvdir dirSep 'P_lrv_4th_b.csv'])
% Ratios: Young and mature larvae to total larvae
writematrix(P_lrv_yng{1,1}',[csvdir dirSep 'P_lrv_yng_m.csv'])
writematrix(P_lrv_yng{1,2}',[csvdir dirSep 'P_lrv_yng_f.csv'])
writematrix(P_lrv_yng{1,3}',[csvdir dirSep 'P_lrv_yng_b.csv'])
writematrix(P_lrv_mat{1,1}',[csvdir dirSep 'P_lrv_mat_m.csv'])
writematrix(P_lrv_mat{1,2}',[csvdir dirSep 'P_lrv_mat_f.csv'])
writematrix(P_lrv_mat{1,3}',[csvdir dirSep 'P_lrv_mat_b.csv'])
% Ratios: Sex-based ratios for all life stages
% Male to all
writematrix(P_m2a{1,1}',[csvdir dirSep 'P_m2a_eggs.csv'])
writematrix(P_m2a{2,1}',[csvdir dirSep 'P_m2a_lrv_1st.csv'])
writematrix(P_m2a{3,1}',[csvdir dirSep 'P_m2a_lrv_2nd.csv'])
writematrix(P_m2a{4,1}',[csvdir dirSep 'P_m2a_lrv_3rd.csv'])
writematrix(P_m2a{5,1}',[csvdir dirSep 'P_m2a_lrv_4th.csv'])
writematrix(P_m2a{6,1}',[csvdir dirSep 'P_m2a_mid.csv'])
% Female to all
writematrix(P_f2a{1,1}',[csvdir dirSep 'P_f2a_eggs.csv'])
writematrix(P_f2a{2,1}',[csvdir dirSep 'P_f2a_lrv_1st.csv'])
writematrix(P_f2a{3,1}',[csvdir dirSep 'P_f2a_lrv_2nd.csv'])
writematrix(P_f2a{4,1}',[csvdir dirSep 'P_f2a_lrv_3rd.csv'])
writematrix(P_f2a{5,1}',[csvdir dirSep 'P_f2a_lrv_4th.csv'])
writematrix(P_f2a{6,1}',[csvdir dirSep 'P_f2a_mid.csv'])
% Male to female
writematrix(P_m2f{1,1}',[csvdir dirSep 'P_m2f_eggs.csv'])
writematrix(P_m2f{2,1}',[csvdir dirSep 'P_m2f_lrv_1st.csv'])
writematrix(P_m2f{3,1}',[csvdir dirSep 'P_m2f_lrv_2nd.csv'])
writematrix(P_m2f{4,1}',[csvdir dirSep 'P_m2f_lrv_3rd.csv'])
writematrix(P_m2f{5,1}',[csvdir dirSep 'P_m2f_lrv_4th.csv'])
writematrix(P_m2f{6,1}',[csvdir dirSep 'P_m2f_mid.csv'])
% Ratios: Sex-based larvae-exclusive ratios
writematrix(P_m2a_lrv_yng',[csvdir dirSep 'P_m2a_lrv_yng.csv'])
writematrix(P_m2a_lrv_mat',[csvdir dirSep 'P_m2a_lrv_mat.csv'])
writematrix(P_m2a_lrv_all',[csvdir dirSep 'P_m2a_lrv_all.csv'])
writematrix(P_f2a_lrv_yng',[csvdir dirSep 'P_f2a_lrv_yng.csv'])
writematrix(P_f2a_lrv_mat',[csvdir dirSep 'P_f2a_lrv_yng.csv'])
writematrix(P_f2a_lrv_all',[csvdir dirSep 'P_f2a_lrv_all.csv'])
writematrix(P_m2f_lrv_yng',[csvdir dirSep 'P_m2f_lrv_yng.csv'])
writematrix(P_m2f_lrv_mat',[csvdir dirSep 'P_m2f_lrv_mat.csv'])
writematrix(P_m2f_lrv_all',[csvdir dirSep 'P_m2f_lrv_all.csv'])
% GDDs
%writematrix(GDD{1,1}',[csvdir dirSep 'GDD_eggs_m.csv'])
%writematrix(GDD{1,2}',[csvdir dirSep 'GDD_eggs_f.csv'])
%writematrix(GDD{2,1}',[csvdir dirSep 'GDD_lrv_1st_m.csv'])
%writematrix(GDD{2,2}',[csvdir dirSep 'GDD_lrv_1st_f.csv'])
%writematrix(GDD{3,1}',[csvdir dirSep 'GDD_lrv_2nd_m.csv'])
%writematrix(GDD{3,2}',[csvdir dirSep 'GDD_lrv_2nd_f.csv'])
%writematrix(GDD{4,1}',[csvdir dirSep 'GDD_lrv_3rd_m.csv'])
%writematrix(GDD{4,2}',[csvdir dirSep 'GDD_lrv_3rd_f.csv'])
%writematrix(GDD{5,1}',[csvdir dirSep 'GDD_lrv_4th_m.csv'])
%writematrix(GDD{5,2}',[csvdir dirSep 'GDD_lrv_4th_f.csv'])
% GDD model: mean
writematrix(GDD_mu{1,1}',[csvdir dirSep 'GDD_mu_eggs_m.csv'])
writematrix(GDD_mu{1,2}',[csvdir dirSep 'GDD_mu_eggs_f.csv'])
writematrix(GDD_mu{2,1}',[csvdir dirSep 'GDD_mu_lrv_1st_m.csv'])
writematrix(GDD_mu{2,2}',[csvdir dirSep 'GDD_mu_lrv_1st_f.csv'])
writematrix(GDD_mu{3,1}',[csvdir dirSep 'GDD_mu_lrv_2nd_m.csv'])
writematrix(GDD_mu{3,2}',[csvdir dirSep 'GDD_mu_lrv_2nd_f.csv'])
writematrix(GDD_mu{4,1}',[csvdir dirSep 'GDD_mu_lrv_3rd_m.csv'])
writematrix(GDD_mu{4,2}',[csvdir dirSep 'GDD_mu_lrv_3rd_f.csv'])
writematrix(GDD_mu{5,1}',[csvdir dirSep 'GDD_mu_lrv_4th_m.csv'])
writematrix(GDD_mu{5,2}',[csvdir dirSep 'GDD_mu_lrv_4th_f.csv'])
% GDD model: standard deviation
writematrix(GDD_sd{1,1}',[csvdir dirSep 'GDD_sd_eggs_m.csv'])
writematrix(GDD_sd{1,2}',[csvdir dirSep 'GDD_sd_eggs_f.csv'])
writematrix(GDD_sd{2,1}',[csvdir dirSep 'GDD_sd_lrv_1st_m.csv'])
writematrix(GDD_sd{2,2}',[csvdir dirSep 'GDD_sd_lrv_1st_f.csv'])
writematrix(GDD_sd{3,1}',[csvdir dirSep 'GDD_sd_lrv_2nd_m.csv'])
writematrix(GDD_sd{3,2}',[csvdir dirSep 'GDD_sd_lrv_2nd_f.csv'])
writematrix(GDD_sd{4,1}',[csvdir dirSep 'GDD_sd_lrv_3rd_m.csv'])
writematrix(GDD_sd{4,2}',[csvdir dirSep 'GDD_sd_lrv_3rd_f.csv'])
writematrix(GDD_sd{5,1}',[csvdir dirSep 'GDD_sd_lrv_4th_m.csv'])
writematrix(GDD_sd{5,2}',[csvdir dirSep 'GDD_sd_lrv_4th_f.csv'])
% Flags and counters
writematrix(Bti_season',[csvdir dirSep 'Bti_season.csv'])
writematrix(Bti_apply',[csvdir dirSep 'Bti_apply.csv'])
writematrix(Bti_app_no',[csvdir dirSep 'Bti_app_no.csv'])
writematrix(Bti_dates',[csvdir dirSep 'Bti_dates.csv'])
% Growth rates
%writematrix(p{1,1}(1,:)',[csvdir dirSep 'p_eggs_m.csv'])
%writematrix(p{1,2}(1,:)',[csvdir dirSep 'p_eggs_f.csv'])
%writematrix(p{2,1}(1,:)',[csvdir dirSep 'p_lrv_1st_m.csv'])
%writematrix(p{2,2}(1,:)',[csvdir dirSep 'p_lrv_1st_f.csv'])
%writematrix(p{3,1}(1,:)',[csvdir dirSep 'p_lrv_2nd_m.csv'])
%writematrix(p{3,2}(1,:)',[csvdir dirSep 'p_lrv_2nd_f.csv'])
%writematrix(p{4,1}(1,:)',[csvdir dirSep 'p_lrv_3rd_m.csv'])
%writematrix(p{4,2}(1,:)',[csvdir dirSep 'p_lrv_3rd_f.csv'])
%writematrix(p{5,1}(1,:)',[csvdir dirSep 'p_lrv_4th_m.csv'])
%writematrix(p{5,2}(1,:)',[csvdir dirSep 'p_lrv_4th_f.csv'])
%writematrix(p{6,1}(1,:)',[csvdir dirSep 'p_mid_m.csv'])
%writematrix(p{6,2}(1,:)',[csvdir dirSep 'p_mid_f.csv'])
% Loss rates
writematrix(l{1,1}(1,:)',[csvdir dirSep 'l_eggs_m.csv'])
writematrix(l{1,2}(1,:)',[csvdir dirSep 'l_eggs_f.csv'])
writematrix(l{2,1}(1,:)',[csvdir dirSep 'l_lrv_1st_m.csv'])
writematrix(l{2,2}(1,:)',[csvdir dirSep 'l_lrv_1st_f.csv'])
writematrix(l{3,1}(1,:)',[csvdir dirSep 'l_lrv_2nd_m.csv'])
writematrix(l{3,2}(1,:)',[csvdir dirSep 'l_lrv_2nd_f.csv'])
writematrix(l{4,1}(1,:)',[csvdir dirSep 'l_lrv_3rd_m.csv'])
writematrix(l{4,2}(1,:)',[csvdir dirSep 'l_lrv_3rd_f.csv'])
writematrix(l{5,1}(1,:)',[csvdir dirSep 'l_lrv_4th_m.csv'])
writematrix(l{5,2}(1,:)',[csvdir dirSep 'l_lrv_4th_f.csv'])
writematrix(l{6,1}(1,:)',[csvdir dirSep 'l_mid_m.csv'])
writematrix(l{6,2}(1,:)',[csvdir dirSep 'l_mid_f.csv'])